services:
  db:
    image: postgres:16.4
    container_name: mathlab-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: mathlearn
      POSTGRES_USER: ml
      POSTGRES_PASSWORD: mlpass
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
