version: '3.9'
services:
  db:
    image: postgres:16
    container_name: mathlab-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ml
      POSTGRES_PASSWORD: mlpass
      POSTGRES_DB: mathlearn
    ports:
      - "5433:5432"   # UWAGA: tutaj zmieniamy na 5433
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
